# Generated by Django 5.0.1 on 2024-02-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_product_quantity_composition_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='composition',
            unique_together={('dish', 'product')},
        ),
    ]
